const QUICK_LOOK_PREVIEWABLE_EXTENSIONS = new Set([
  '.avif',
  '.aiff',
  '.avi',
  '.bmp',
  '.csv',
  '.doc',
  '.docx',
  '.flac',
  '.gif',
  '.heic',
  '.heif',
  '.htm',
  '.html',
  '.ico',
  '.jpeg',
  '.jpg',
  '.jfif',
  '.key',
  '.m4a',
  '.m4v',
  '.md',
  '.mov',
  '.mp3',
  '.mp4',
  '.numbers',
  '.odp',
  '.ods',
  '.odt',
  '.pages',
  '.pdf',
  '.png',
  '.ppt',
  '.pptx',
  '.rtf',
  '.rtfd',
  '.svg',
  '.tsv',
  '.tif',
  '.tiff',
  '.txt',
  '.wav',
  '.webm',
  '.webp',
  '.xls',
  '.xlsm',
  '.xlsx',
])

export function isQuickLookPreviewablePath(path: string): boolean {
  const fileName = path.split(/[\\/]/).pop() ?? ''
  const dot = fileName.lastIndexOf('.')
  const extension = dot >= 0 ? fileName.slice(dot).toLowerCase() : ''
  return QUICK_LOOK_PREVIEWABLE_EXTENSIONS.has(extension)
}
